require('dotenv').config();
const path=require('path'),crypto=require('crypto'),http=require('http'),fs=require('fs');
const express=require('express'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),session=require('express-session');
const SQLiteStore=require('connect-sqlite3')(session); const Database=require('better-sqlite3'); const bcrypt=require('bcryptjs');
const {Server}=require('socket.io'); const {z}=require('zod');
let Stripe=null; try{Stripe=require('stripe');}catch{}
const app=express(), server=http.createServer(app); const io=new Server(server,{cors:false,transports:['websocket','polling'],maxHttpBufferSize:100000});
const PORT=Number(process.env.PORT||3000), PROD=process.env.NODE_ENV==='production'; const ADMIN_EMAIL=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase(), SESSION_SECRET=process.env.SESSION_SECRET;
if(PROD&&(!SESSION_SECRET||SESSION_SECRET.length<32))throw new Error('SESSION_SECRET doit contenir au moins 32 caractères.'); app.set('trust proxy',PROD?1:false);app.disable('x-powered-by');
const dataDir=path.join(__dirname,'data');fs.mkdirSync(dataDir,{recursive:true});const db=new Database(path.join(dataDir,'app.db'));db.pragma('journal_mode=WAL');db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,first_name TEXT NOT NULL,last_name TEXT NOT NULL,email TEXT NOT NULL UNIQUE COLLATE NOCASE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'client',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_login_at TEXT,phone TEXT DEFAULT '',bio TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',duration INTEGER NOT NULL DEFAULT 60,price_cents INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS availability(id INTEGER PRIMARY KEY AUTOINCREMENT,weekday INTEGER NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS blocked_slots(id INTEGER PRIMARY KEY AUTOINCREMENT,start_at TEXT NOT NULL,end_at TEXT NOT NULL,reason TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS consultations(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,service_id INTEGER NOT NULL,subject TEXT NOT NULL,message TEXT NOT NULL DEFAULT '',requested_at TEXT NOT NULL,duration INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',payment_status TEXT NOT NULL DEFAULT 'unpaid',stripe_session_id TEXT,room_token TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at TEXT,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(service_id) REFERENCES services(id));CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,action TEXT NOT NULL,metadata TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_consult_user ON consultations(user_id);CREATE INDEX IF NOT EXISTS idx_consult_date ON consultations(requested_at);`);
if(!db.prepare('SELECT COUNT(*) n FROM services').get().n)db.prepare('INSERT INTO services(name,description,duration,price_cents) VALUES(?,?,?,?)').run('Consultation intuitive','Une séance privée en visioconférence, centrée sur votre demande.',60,6000);
const sessionMiddleware=session({name:PROD?'__Host-ladc.sid':'ladc.sid',store:new SQLiteStore({db:'sessions.db',dir:dataDir}),secret:SESSION_SECRET||'dev-only-change-this-secret-before-production',resave:false,saveUninitialized:false,rolling:true,cookie:{httpOnly:true,secure:PROD,sameSite:'lax',maxAge:8*60*60*1000,path:'/'}});
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','https://miro.medium.com'],connectSrc:["'self'",'ws:','wss:'],mediaSrc:["'self'",'blob:'],fontSrc:["'self'",'data:'],objectSrc:["'none'"],frameAncestors:["'none'"],formAction:["'self'"]}},crossOriginResourcePolicy:{policy:'cross-origin'},referrerPolicy:{policy:'strict-origin-when-cross-origin'}}));
const apiLimiter=rateLimit({windowMs:60000,limit:150,standardHeaders:'draft-7',legacyHeaders:false}),authLimiter=rateLimit({windowMs:15*60000,limit:12,standardHeaders:'draft-7',legacyHeaders:false});app.use(express.json({limit:'100kb'}));app.use(express.urlencoded({extended:false,limit:'100kb'}));app.use(sessionMiddleware);app.use('/api',apiLimiter);
const email=x=>String(x||'').trim().toLowerCase(),csrf=req=>{if(!req.session.csrfToken)req.session.csrfToken=crypto.randomBytes(32).toString('hex');return req.session.csrfToken};
function safeUser(u){return u?{id:u.id,firstName:u.first_name,lastName:u.last_name,email:u.email,phone:u.phone||'',bio:u.bio||'',role:u.role,createdAt:u.created_at}:null}function auth(req,res,n){if(!req.session.userId)return res.status(401).json({error:'Authentification requise.'});n()}function owner(req,res,n){if(req.session.role!=='owner')return res.status(403).json({error:'Accès propriétaire requis.'});n()}function audit(req,a,m={}){try{db.prepare('INSERT INTO audit_logs(user_id,action,metadata) VALUES(?,?,?)').run(req.session.userId||null,a,JSON.stringify(m))}catch{}}
function csrfCheck(req,res,n){const a=req.get('x-csrf-token'),b=req.session.csrfToken;if(!a||!b||a.length!==b.length||!crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b)))return res.status(403).json({error:'Jeton de sécurité invalide.'});n()}
app.use('/api',(req,res,n)=>{if(!['POST','PATCH','PUT','DELETE'].includes(req.method))return n();const o=req.get('origin');if(!o)return n();try{if(new URL(o).host!==req.get('host'))return res.status(403).json({error:'Origine non autorisée.'})}catch{return res.status(403).json({error:'Origine invalide.'})}n()});
const reg=z.object({firstName:z.string().trim().min(2).max(60),lastName:z.string().trim().min(2).max(60),email:z.string().email().max(180),password:z.string().min(12).max(128).regex(/[a-z]/).regex(/[A-Z]/).regex(/[0-9]/)}),login=z.object({email:z.string().email().max(180),password:z.string().min(1).max(128)}),booking=z.object({serviceId:z.coerce.number().int().positive().default(1),subject:z.string().trim().min(3).max(120),message:z.string().trim().max(1500).default(''),requestedAt:z.string().datetime({offset:true})});
app.get('/api/csrf',(req,res)=>res.json({csrfToken:csrf(req)}));app.get('/api/me',(req,res)=>{const u=req.session.userId&&db.prepare('SELECT * FROM users WHERE id=?').get(req.session.userId);res.json({user:safeUser(u)})});
app.post('/api/auth/register',authLimiter,csrfCheck,async(req,res)=>{const p=reg.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Vérifiez les informations saisies.'});const e=email(p.data.email);if(db.prepare('SELECT id FROM users WHERE email=?').get(e))return res.status(409).json({error:'Un compte existe déjà avec cette adresse.'});const role=ADMIN_EMAIL&&e===ADMIN_EMAIL?'owner':'client',h=await bcrypt.hash(p.data.password,12),i=db.prepare('INSERT INTO users(first_name,last_name,email,password_hash,role) VALUES(?,?,?,?,?)').run(p.data.firstName,p.data.lastName,e,h,role);req.session.regenerate(err=>{if(err)return res.status(500).json({error:'Impossible de créer la session.'});req.session.userId=Number(i.lastInsertRowid);req.session.role=role;req.session.csrfToken=crypto.randomBytes(32).toString('hex');audit(req,'account.created');res.status(201).json({user:safeUser(db.prepare('SELECT * FROM users WHERE id=?').get(i.lastInsertRowid)),csrfToken:req.session.csrfToken})})});
app.post('/api/auth/login',authLimiter,csrfCheck,async(req,res)=>{const p=login.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Identifiants invalides.'});const u=db.prepare('SELECT * FROM users WHERE email=?').get(email(p.data.email));if(!u||!(await bcrypt.compare(p.data.password,u.password_hash)))return res.status(401).json({error:'Email ou mot de passe incorrect.'});const role=ADMIN_EMAIL&&u.email===ADMIN_EMAIL?'owner':u.role;db.prepare('UPDATE users SET role=?,last_login_at=CURRENT_TIMESTAMP WHERE id=?').run(role,u.id);req.session.regenerate(err=>{if(err)return res.status(500).json({error:'Impossible de créer la session.'});req.session.userId=u.id;req.session.role=role;req.session.csrfToken=crypto.randomBytes(32).toString('hex');audit(req,'account.login');res.json({user:{...safeUser(u),role},csrfToken:req.session.csrfToken})})});
app.post('/api/auth/logout',csrfCheck,(req,res)=>req.session.destroy(()=>{res.clearCookie(PROD?'__Host-ladc.sid':'ladc.sid',{path:'/'});res.json({ok:true})}));
app.patch('/api/profile',auth,csrfCheck,(req,res)=>{const p=z.object({firstName:z.string().trim().min(2).max(60),lastName:z.string().trim().min(2).max(60),phone:z.string().trim().max(30).default(''),bio:z.string().trim().max(500).default('')}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Profil invalide.'});db.prepare('UPDATE users SET first_name=?,last_name=?,phone=?,bio=? WHERE id=?').run(p.data.firstName,p.data.lastName,p.data.phone,p.data.bio,req.session.userId);res.json({user:safeUser(db.prepare('SELECT * FROM users WHERE id=?').get(req.session.userId))})});
app.patch('/api/profile/password',auth,csrfCheck,async(req,res)=>{const p=z.object({currentPassword:z.string(),newPassword:z.string().min(12).max(128).regex(/[a-z]/).regex(/[A-Z]/).regex(/[0-9]/)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Nouveau mot de passe trop faible.'});const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.session.userId);if(!(await bcrypt.compare(p.data.currentPassword,u.password_hash)))return res.status(400).json({error:'Mot de passe actuel incorrect.'});db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(await bcrypt.hash(p.data.newPassword,12),u.id);res.json({ok:true})});
app.get('/api/services',(req,res)=>res.json({services:db.prepare('SELECT id,name,description,duration,price_cents priceCents FROM services WHERE active=1').all()}));
const mins=s=>{const[a,b]=String(s).split(':').map(Number);return a*60+b};
app.get('/api/availability',auth,(req,res)=>{const start=new Date(String(req.query.from||Date.now())),days=Math.min(31,Math.max(1,Number(req.query.days||14))),service=db.prepare('SELECT * FROM services WHERE id=? AND active=1').get(Number(req.query.serviceId)||1);if(!service)return res.status(404).json({error:'Service introuvable.'});const rulesCount=db.prepare('SELECT COUNT(*) n FROM availability WHERE active=1').get().n,out=[];for(let i=0;i<days;i++){const d=new Date(start);d.setHours(0,0,0,0);d.setDate(d.getDate()+i);const rules=db.prepare('SELECT * FROM availability WHERE weekday=? AND active=1').all(d.getDay());for(const r of rulesCount?(rules):[{start_time:'09:00',end_time:'18:00'}])for(let m=mins(r.start_time);m+service.duration<=mins(r.end_time);m+=30){const slot=new Date(d);slot.setHours(Math.floor(m/60),m%60,0,0);const end=new Date(slot.getTime()+service.duration*60000);if(slot<Date.now()+30*60000)continue;const busy=db.prepare("SELECT id FROM consultations WHERE status IN ('pending','confirmed') AND requested_at<? AND datetime(requested_at,'+'||duration||' minutes')>?").get(end.toISOString(),slot.toISOString()),blocked=db.prepare('SELECT id FROM blocked_slots WHERE start_at<? AND end_at>?').get(end.toISOString(),slot.toISOString());if(!busy&&!blocked)out.push({start:slot.toISOString(),end:end.toISOString()})}}res.json({slots:out,service})});
app.get('/api/consultations',auth,(req,res)=>res.json({consultations:req.session.role==='owner'?db.prepare('SELECT c.*,u.first_name,u.last_name,u.email,s.name service_name,s.price_cents FROM consultations c JOIN users u ON u.id=c.user_id JOIN services s ON s.id=c.service_id ORDER BY c.requested_at').all():db.prepare('SELECT c.*,s.name service_name,s.price_cents FROM consultations c JOIN services s ON s.id=c.service_id WHERE c.user_id=? ORDER BY c.requested_at').all(req.session.userId)}));
app.post('/api/consultations',auth,csrfCheck,(req,res)=>{const p=booking.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Réservation invalide.'});const s=db.prepare('SELECT * FROM services WHERE id=? AND active=1').get(p.data.serviceId);if(!s)return res.status(404).json({error:'Service introuvable.'});const start=new Date(p.data.requestedAt),end=new Date(start.getTime()+s.duration*60000);if(start<Date.now()+30*60000)return res.status(400).json({error:'Choisissez un créneau futur.'});const busy=db.prepare("SELECT id FROM consultations WHERE status IN ('pending','confirmed') AND requested_at<? AND datetime(requested_at,'+'||duration||' minutes')>?").get(end.toISOString(),start.toISOString());if(busy)return res.status(409).json({error:'Ce créneau vient d’être réservé.'});const token=crypto.randomBytes(24).toString('hex'),i=db.prepare('INSERT INTO consultations(user_id,service_id,subject,message,requested_at,duration,room_token) VALUES(?,?,?,?,?,?,?)').run(req.session.userId,s.id,p.data.subject,p.data.message,start.toISOString(),s.duration,token);audit(req,'booking.created',{id:i.lastInsertRowid});res.status(201).json({consultation:db.prepare('SELECT * FROM consultations WHERE id=?').get(i.lastInsertRowid)})});
app.patch('/api/consultations/:id/status',owner,csrfCheck,(req,res)=>{const p=z.object({status:z.enum(['pending','confirmed','completed','cancelled'])}).safeParse(req.body),id=Number(req.params.id);if(!p.success)return res.status(400).json({error:'Statut invalide.'});const i=db.prepare('UPDATE consultations SET status=?,completed_at=CASE WHEN ?="completed" THEN CURRENT_TIMESTAMP ELSE completed_at END WHERE id=?').run(p.data.status,p.data.status,id);if(!i.changes)return res.status(404).json({error:'Consultation introuvable.'});res.json({ok:true})});
app.delete('/api/consultations/:id',auth,csrfCheck,(req,res)=>{const c=db.prepare('SELECT * FROM consultations WHERE id=?').get(Number(req.params.id));if(!c||(req.session.role!=='owner'&&c.user_id!==req.session.userId))return res.status(404).json({error:'Consultation introuvable.'});if(c.status==='completed')return res.status(400).json({error:'Consultation terminée.'});db.prepare('UPDATE consultations SET status="cancelled" WHERE id=?').run(c.id);res.json({ok:true})});
app.get('/api/consultations/:id/access',auth,(req,res)=>{const c=db.prepare('SELECT c.*,u.first_name,u.last_name,s.name service_name FROM consultations c JOIN users u ON u.id=c.user_id JOIN services s ON s.id=c.service_id WHERE c.id=?').get(Number(req.params.id));if(!c)return res.status(404).json({error:'Consultation introuvable.'});if(req.session.role!=='owner'&&c.user_id!==req.session.userId)return res.status(403).json({error:'Accès refusé.'});if(c.status!=='confirmed')return res.status(409).json({error:'Cette consultation doit être confirmée.'});res.json({consultation:c,iceServers:getIceServers()})});
app.get('/api/admin/stats',owner,(req,res)=>res.json({clients:db.prepare("SELECT COUNT(*) n FROM users WHERE role='client'").get().n,upcoming:db.prepare("SELECT COUNT(*) n FROM consultations WHERE status='confirmed' AND requested_at>=CURRENT_TIMESTAMP").get().n,pending:db.prepare("SELECT COUNT(*) n FROM consultations WHERE status='pending'").get().n,completed:db.prepare("SELECT COUNT(*) n FROM consultations WHERE status='completed'").get().n,revenue:db.prepare("SELECT COALESCE(SUM(s.price_cents),0) n FROM consultations c JOIN services s ON s.id=c.service_id WHERE c.status='completed'").get().n}));app.get('/api/admin/clients',owner,(req,res)=>res.json({clients:db.prepare("SELECT id,first_name firstName,last_name lastName,email,phone,created_at createdAt,last_login_at lastLoginAt FROM users WHERE role='client' ORDER BY created_at DESC").all()}));
app.get('/api/admin/availability',owner,(req,res)=>res.json({rules:db.prepare('SELECT * FROM availability ORDER BY weekday,start_time').all(),blocked:db.prepare('SELECT * FROM blocked_slots ORDER BY start_at').all()}));app.post('/api/admin/availability',owner,csrfCheck,(req,res)=>{const p=z.object({weekday:z.coerce.number().int().min(0).max(6),startTime:z.string().regex(/^\d{2}:\d{2}$/),endTime:z.string().regex(/^\d{2}:\d{2}$/)}).safeParse(req.body);if(!p.success||mins(p.data.startTime)>=mins(p.data.endTime))return res.status(400).json({error:'Horaires invalides.'});db.prepare('INSERT INTO availability(weekday,start_time,end_time) VALUES(?,?,?)').run(p.data.weekday,p.data.startTime,p.data.endTime);res.json({ok:true})});app.delete('/api/admin/availability/:id',owner,csrfCheck,(req,res)=>{db.prepare('DELETE FROM availability WHERE id=?').run(Number(req.params.id));res.json({ok:true})});
app.post('/api/payments/create-checkout',auth,csrfCheck,async(req,res)=>{if(!Stripe||!process.env.STRIPE_SECRET_KEY)return res.status(503).json({error:'Paiement non configuré : ajoutez STRIPE_SECRET_KEY dans .env.'});const c=db.prepare('SELECT c.*,s.name,s.price_cents FROM consultations c JOIN services s ON s.id=c.service_id WHERE c.id=? AND c.user_id=?').get(Number(req.body.consultationId),req.session.userId);if(!c)return res.status(404).json({error:'Consultation introuvable.'});const stripe=new Stripe(process.env.STRIPE_SECRET_KEY),x=await stripe.checkout.sessions.create({mode:'payment',line_items:[{price_data:{currency:'eur',product_data:{name:c.name},unit_amount:c.price_cents},quantity:1}],metadata:{consultationId:String(c.id)},success_url:process.env.STRIPE_SUCCESS_URL||`${req.protocol}://${req.get('host')}/espace?payment=success`,cancel_url:process.env.STRIPE_CANCEL_URL||`${req.protocol}://${req.get('host')}/espace?payment=cancelled`});db.prepare('UPDATE consultations SET stripe_session_id=?,payment_status="pending" WHERE id=?').run(x.id,c.id);res.json({url:x.url})});
app.post('/api/payments/webhook',express.raw({type:'application/json'}),(req,res)=>{if(!Stripe||!process.env.STRIPE_SECRET_KEY||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).end();try{const stripe=new Stripe(process.env.STRIPE_SECRET_KEY),e=stripe.webhooks.constructEvent(req.body,req.get('stripe-signature'),process.env.STRIPE_WEBHOOK_SECRET);if(e.type==='checkout.session.completed')db.prepare('UPDATE consultations SET payment_status="paid" WHERE id=?').run(Number(e.data.object.metadata?.consultationId));res.json({received:true})}catch(e){res.status(400).send(e.message)}});
function getIceServers(){const s=[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}];if(process.env.TURN_URL&&process.env.TURN_USERNAME&&process.env.TURN_CREDENTIAL)s.push({urls:process.env.TURN_URL.split(',').map(x=>x.trim()).filter(Boolean),username:process.env.TURN_USERNAME,credential:process.env.TURN_CREDENTIAL});return s}
io.engine.use(sessionMiddleware);io.use((s,n)=>s.request.session?.userId?n():n(new Error('unauthorized')));io.on('connection',s=>{s.on('join-consultation',({consultationId})=>{const id=Number(consultationId),u=s.request.session,c=db.prepare('SELECT * FROM consultations WHERE id=?').get(id);if(!c||c.status!=='confirmed'||(u.role!=='owner'&&c.user_id!==u.userId))return;const room=`consultation:${id}:${c.room_token}`;if((io.sockets.adapter.rooms.get(room)?.size||0)>=2)return s.emit('room-full');s.join(room);s.data.room=room;s.emit('room-joined',{initiator:(io.sockets.adapter.rooms.get(room)?.size||0)===1});s.to(room).emit('peer-joined')});for(const e of ['offer','answer','ice-candidate'])s.on(e,d=>s.data.room&&s.to(s.data.room).emit(e,d));s.on('disconnect',()=>s.data.room&&s.to(s.data.room).emit('peer-left'))});
app.use(express.static(path.join(__dirname,'public'),{maxAge:PROD?'1d':0}));app.get('/{*splat}',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));server.listen(PORT,()=>console.log(`L'Art de la Connexion — http://localhost:${PORT}`));
